# .cargo/config.toml

[alias]
# `cargo rerun` is short a convenient shorthand
oxdraw = "run --package oxdraw --"

[env]
# Set environment variables
APP_NAME = "Oxdraw"
APP_DESC = "A virtual space for sketching hand drawing and whiteboards in rust"
APP_AUTHOR = "By Quadri Adekunle and contributors"

# Build specific configuration

# # On Windows
# # ```
# # cargo install -f cargo-binutils
# # rustup component add llvm-tools-preview
# # ```
# [target.x86_64-pc-windows-msvc]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# [target.x86_64-pc-windows-gnu]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# # On Linux:
# # - Ubuntu, `sudo apt-get install lld clang`
# # - Arch, `sudo pacman -S lld clang`
# [target.x86_64-unknown-linux-gnu]
# rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]

# [target.x86_64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]
# [target.aarch64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# Optional: Uncommenting the following improves compile times, but reduces the amount of debug info to 'line number tables only'
# In most cases the gains are negligible, but if you are on macos and have slow compile times you should see significant gains.
[profile.release]
debug = 0
