name: cargo docs

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  doc_tests:
    name: doc tests
    runs-on: ubuntu-latest

    steps:
      - name: install libgtk-dev
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - run: cargo test --doc
